#!/bin/sh
commit_msg=$(cat "$1")

# Basic regex check
if ! echo "$commit_msg" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|revert)(\(.+\))?: .+"; then
  echo "Invalid commit message format!" >&2
  echo "Example: feat: add new login endpoint, For more info: https://www.conventionalcommits.org" >&2
  exit 1
fi