name: Semantic Release

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'src/VERSION'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch --tags --force
          git fetch --prune --unshallow

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install semantic-release globally
      - name: Install semantic-release
        run: |
          npm install -g \
            semantic-release \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/changelog \
            @semantic-release/exec

      - name: Remove existing tag if exists (to handle history rewrites)
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -n "$TAG" ]; then
            echo "Removing existing tag: $TAG"
            git tag -d "$TAG" || true
            git push --delete origin "$TAG" || true
          fi

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
